wandb_name: nist20_scaffold_fragnnet_d3_s0_unmerged
wandb_group: nist20_scaffold_fragnnet_d3

# seed
seed: 397623

# data stuff
spec_fp: data/proc/nist20/spec_df.pkl
mol_fp: data/proc/nist20/mol_df.pkl
split_dp: data/split/nist20_scaffold
frag_dp: data/frag/nist20_d3/dags
frag_params:
  pyg_edge_feats: []
  pyg_edges: False
  pyg_bigraph: False
  preload: True
  preprocess: True
spec_params:
  merge: False
  nce: True
  merge_keep_ces: False
  preprocess: True
mol_params:
  preprocess: True

# model stuff
frag_gnn_type: NodeMLP
num_depth: 4
num_hs: 4
ce_insert_type: embed
ce_insert_location: mlp
ce_insert_merge: True
mol_pool_type: mean
frag_pool_type: mean
mol_normalization: batch
mol_hidden_size: 256
mol_dropout: 0.2
frag_hidden_size: 256
frag_normalization: graph
frag_embed_combine: avg
frag_pool_combine: subtract
frag_dropout: 0.1
mlp_normalization: layer
mlp_hidden_size: 64
mlp_dropout: 0.2

# loss stuff
mask_null_formula: False
predict_oos: True
oos_tolerance_multiple: 1
oos_loss: True
gaussian_renormalize: True
sparse_cosine_similarity: True
loss_vectorized: True
loss_batch_size: 16
skip_extra_losses: True
group_sampler: False
simple_group_sampler: False
train_sample_weight: none
eval_sample_weight: none

# optimization stuff
train_batch_size: 32
eval_batch_size: 32
accumulate_grad_batches: 4
gradient_clip_val: 5.0
lr: 0.0003033
weight_decay: 0.01
accelerator: gpu
devices: 1
min_epochs: 500
max_epochs: 500
lr_schedule: False
debug_overfit: False
upload_checkpoints: True
checkpoint_metric: val_cos_sim_0.01_epoch/mean
auxiliary_scores:
- cos_sim
eval_mz_bin_res:
- 0.01
precision: 32
use_tensor_float32: True
automatic_optimization: True
dynamic_batch_sampler: False
pl_enable_progress_bar: True
compile: True
